# Generated by Django 2.2.1 on 2019-05-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('date_published', models.DateField(blank=True)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('type_of_book', models.CharField(choices=[('One of Novel', 'One of Novel'), ('Documentation', 'Documentation'), ('Other', 'Other')], default='Other', max_length=25)),
            ],
        ),
    ]
